### ISSUE TITLE
Only the "color dot" is clickable

### ISSUE THREAD

**Issue by vincentdesmares** [flaming-cl/editorjs-text-color-plugin#1]
First, thank you very much for participating to the editorJs community!

About the issue, the tooltip action button is composer of a letter "A" and a color dot.
When the cursor hover the "A", the cursor icon is not a "pointer" but it is still clickable.
When the cursor hover the "dot", the cursor icon is a "pointer" and shows the color picker.

I feel that it could be a better experience to have only one behavior:

- The cursor should be a pointer is either case
- The color picker should open in either case

What do you think?

**Comment by flaming-cl** [comment]
Hi. Thanks for the feedback. 

I agree with your idea that the tooltip button should not have more than one cursor styling.
Since sometimes users may just want to use a color for multiple times, there would be no need for them to keep seeing the color picker panel.

I've updated a new version of the plugin. You can try in this Demo: [https://flaming-cl.github.io/editorPlugin/](url)

Have a nice weekend.
